# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: wowgoons
:url: http://wowgoons.com
:copyright: 2014
:analytics_code: UA-00000000-0
